POST http://localhost:3003/api/activities
Content-Type: application/json

{
    "name": "Obedece a las profesoras"
}

###
POST http://localhost:3003/api/activities
Content-Type: application/json

{
    "name": "Comportamiento con los compañeros"
}

###
POST http://localhost:3003/api/activities
Content-Type: application/json

{
    "name": "Obedece a los padres"
}

###
POST http://localhost:3003/api/activities
Content-Type: application/json

{
    "name": "Recoge los juguetes"
}

###
POST http://localhost:3003/api/activities
Content-Type: application/json

{
    "name": "No responde de manera altanera a los padres"
}
